Autogenerated tree updates.
merged:

  flora: 523a446b976b43c4ede7fd49048643aaf4812e42
  faustoo: 0977301b537a77c81e5e8d2dd326361bc6f12523
  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  kit-fixups: fcb1b34565c689958d9aad74bb40ad984d386001

diff --git a/net-misc/hylafaxplus/templates/hylafaxplus.tmpl b/net-misc/hylafaxplus/templates/hylafaxplus.tmpl
--- a/net-misc/hylafaxplus/templates/hylafaxplus.tmpl
+++ b/net-misc/hylafaxplus/templates/hylafaxplus.tmpl
@@ -1,46 +1,47 @@
-# Copyright 1999-2018 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=6
+EAPI=7
+
 inherit pam toolchain-funcs
 
 MY_PN="${PN/plus/}"
 MY_P="${MY_PN}-${PV}"
 
+S="${WORKDIR}/${MY_P}"
 DESCRIPTION="Enterprise client-server fax package for class 1 and 2 fax modems"
-HOMEPAGE="http://hylafax.sourceforge.net"
-SRC_URI="mirror://sourceforge/hylafax/${MY_P}.tar.gz"
+HOMEPAGE="https://hylafax.sourceforge.io/"
+SRC_URI="{{ artifacts[0].src_uri }}"
 
 SLOT="0"
 LICENSE="hylafaxplus"
-KEYWORDS="~amd64 ~x86"
-IUSE="jbig html lcms ldap mgetty pam"
+KEYWORDS="*"
+IUSE="html jbig lcms ldap mgetty pam"
 
 DEPEND="
-	>=sys-libs/zlib-1.1.4
 	app-text/ghostscript-gpl
-	virtual/mta
 	media-libs/tiff:0[jbig?]
-	virtual/jpeg:0
-	jbig? ( media-libs/jbigkit )
+	!net-dialup/mgetty[fax]
+	>=sys-libs/zlib-1.1.4
 	virtual/awk
+	virtual/jpeg:0
+	virtual/mta
+	jbig? ( media-libs/jbigkit )
 	lcms? ( media-libs/lcms )
 	ldap? (  net-nds/openldap )
-	pam? ( virtual/pam )
 	mgetty? ( net-dialup/mgetty[-fax] )
-	!net-dialup/mgetty[fax]
+	pam? ( sys-libs/pam )
 "
 RDEPEND="${DEPEND}
-	net-mail/metamail
 	!net-dialup/sendpage
+	net-mail/metamail
 "
 
-S="${WORKDIR}/${MY_P}"
+CONFIG_PROTECT="${CONFIG_PROTECT} /var/spool/fax/etc /usr/lib/fax"
+CONFIG_PROTECT_MASK="${CONFIG_PROTECT_MASK} /var/spool/fax/etc/xferfaxlog"
 
-export CONFIG_PROTECT="${CONFIG_PROTECT} /var/spool/fax/etc /usr/lib/fax"
-export CONFIG_PROTECT_MASK="${CONFIG_PROTECT_MASK} /var/spool/fax/etc/xferfaxlog"
-
-PATCHES=( "${FILESDIR}/ldconfig-patch" )
+PATCHES=(
+	"${FILESDIR}/${PN}-ldconfig.patch"
+)
 
 src_prepare() {
 	default
@@ -49,7 +50,7 @@ src_prepare() {
 	for dir in etc util faxalter faxcover faxd faxmail faxrm faxstat \
 		hfaxd sendfax sendpage ; do
 			sed -i -e "s:-idb:-idb \"nostrip\" -idb:g" \
-				"${dir}"/Makefile.in || die "sed failed"
+				"${dir}"/Makefile.in || die "sed on ${dir}/Makefile.in failed"
 	done
 
 	sed -i -e "s:hostname:hostname -f:g" util/{faxrcvd,pollrcvd}.sh.in || die "sed on hostname failed"
@@ -67,7 +68,8 @@ src_configure() {
 		# eval required for quoting in ${my_conf} to work properly, better way?
 		eval ./configure --nointeractive ${1} || die "./configure failed"
 	}
-	local my_conf="
+
+	local my_conf=(
 		--with-DIR_BIN=/usr/bin
 		--with-DIR_SBIN=/usr/sbin
 		--with-DIR_LIB=/usr/$(get_libdir)
@@ -77,38 +79,41 @@ src_configure() {
 		--with-DIR_LOCKS=/var/lock
 		--with-DIR_MAN=/usr/share/man
 		--with-DIR_SPOOL=/var/spool/fax
-		--with-DIR_HTML=/usr/share/doc/${P}/html
+		--with-DIR_HTML=/usr/share/doc/${PF}/html
 		--with-DIR_CGI="${WORKDIR}"
 		--with-PATH_DPSRIP=/var/spool/fax/bin/ps2fax
-		--with-PATH_IMPRIP=\"\"
+		--with-PATH_IMPRIP=""
 		--with-SYSVINIT=no
 		--with-REGEX=yes
 		--with-LIBTIFF=\"-ltiff -ljpeg -lz\"
 		--with-OPTIMIZER=\"${CFLAGS}\"
 		--with-DSO=auto
-		--with-HTML=$(usex html)"
+		--with-HTML=$(usex html)
+	)
 
 	if use mgetty; then
-		my_conf="${my_conf} \
-			--with-PATH_GETTY=/sbin/mgetty \
-			--with-PATH_EGETTY=/sbin/mgetty \
-			--with-PATH_VGETTY=/usr/sbin/vgetty"
+		my_conf+=(
+			--with-PATH_GETTY=/sbin/mgetty
+			--with-PATH_EGETTY=/sbin/mgetty
+			--with-PATH_VGETTY=/usr/sbin/vgetty
+		)
 	else
 		# GETTY defaults to /sbin/agetty
-		my_conf="${my_conf} \
-			--with-PATH_EGETTY=/bin/false \
-			--with-PATH_VGETTY=/bin/false"
+		my_conf+=(
+			--with-PATH_EGETTY=/bin/false
+			--with-PATH_VGETTY=/bin/false
+		)
 	fi
 
 	#--enable-pam isn't valid
-	use pam || my_conf="${my_conf} $(use_enable pam)"
-	use lcms || my_conf="${my_conf} $(use_enable lcms)"
-	use ldap || my_conf="${my_conf} $(use_enable ldap)"
-	use jbig || my_conf="${my_conf} $(use_enable jbig)"
+	use pam || my_conf+=( $(use_enable pam) )
+	use lcms || my_conf+=( $(use_enable lcms) )
+	use ldap || my_conf+=( $(use_enable ldap) )
+	use jbig || my_conf+=( $(use_enable jbig) )
 
 	tc-export CC CXX AR RANLIB
 
-	do_configure "${my_conf}"
+	do_configure "${my_conf[*]}"
 }
 
 src_compile() {
@@ -139,10 +144,12 @@ src_install() {
 	keepdir /var/spool/fax/{archive,client,etc,pollq,recvq,tmp}
 	keepdir /var/spool/fax/{status,sendq,log,info,doneq,docq,dev}
 
-	generate_files # in this case, it only generates the env.d entry
-
 	einfo "Adding env.d entry for ${PN}"
-	doenvd "${T}/99${PN}"
+	newenvd - 99hylafaxplus <<-EOF
+		PATH="/var/spool/fax/bin"
+		CONFIG_PROTECT="/var/spool/fax/etc /usr/$(get_libdir)/fax"
+		CONFIG_PROTECT_MASK="/var/spool/fax/etc/xferfaxlog"
+	EOF
 
 	newconfd "${FILESDIR}/${PN}-conf" ${PN}
 	newinitd "${FILESDIR}/${PN}-init" ${PN}
@@ -151,12 +158,4 @@ src_install() {
 
 	einstalldocs
 	docinto samples
-}
-
-generate_files() {
-	cat <<-EOF > "${T}/99${PN}"
-	PATH="/var/spool/fax/bin"
-	CONFIG_PROTECT="/var/spool/fax/etc /usr/$(get_libdir)/fax"
-	CONFIG_PROTECT_MASK="/var/spool/fax/etc/xferfaxlog"
-	EOF
 }
