Autogenerated tree updates.
merged:

  flora: 523a446b976b43c4ede7fd49048643aaf4812e42
  faustoo: 808a41a94efd78d19605d8e326b177257bbda4ce
  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  kit-fixups: 67a806e88c07cc14937ac7967be75e8d22671918

diff --git a/net-misc/openvswitch/templates/openvswitch.tmpl b/net-misc/openvswitch/templates/openvswitch.tmpl
--- a/net-misc/openvswitch/templates/openvswitch.tmpl
+++ b/net-misc/openvswitch/templates/openvswitch.tmpl
@@ -1,36 +1,34 @@
-# Copyright 1999-2019 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=6
+EAPI=7
+PYTHON_COMPAT=( python3+ )
 
-PYTHON_COMPAT=( python{2_7,3_5,3_6} )
-
-inherit autotools eutils linux-info linux-mod python-r1 systemd versionator
+inherit autotools linux-info linux-mod python-r1 systemd tmpfiles
 
 DESCRIPTION="Production quality, multilayer virtual switch"
 HOMEPAGE="https://www.openvswitch.org"
-SRC_URI="https://www.openvswitch.org/releases/${P}.tar.gz"
+SRC_URI="{{ artifacts[0].src_uri }}"
 
 LICENSE="Apache-2.0 GPL-2"
 SLOT="0"
-KEYWORDS="amd64 ~arm64 ~x86"
-IUSE="debug modules monitor +ssl"
+KEYWORDS="*"
+IUSE="debug modules monitor +ssl systemd"
 REQUIRED_USE="${PYTHON_REQUIRED_USE}"
 
 RDEPEND="
 	ssl? ( dev-libs/openssl:0= )
 	${PYTHON_DEPS}
-	~dev-python/ovs-2.7.2[${PYTHON_USEDEP}]
-	|| (
-		dev-python/twisted[conch,${PYTHON_USEDEP}]
-		dev-python/twisted-web[${PYTHON_USEDEP}]
-	)
+	dev-python/ovs[${PYTHON_USEDEP}]
+	dev-python/twisted[conch,${PYTHON_USEDEP}]
 	dev-python/zope-interface[${PYTHON_USEDEP}]
 	debug? ( dev-lang/perl )"
 DEPEND="${RDEPEND}
-	virtual/pkgconfig"
+	sys-apps/util-linux[caps]"
+BDEPEND="virtual/pkgconfig"
 
-PATCHES="${FILESDIR}/xcp-interface-reconfigure-2.3.2.patch"
+PATCHES="
+	"${FILESDIR}/xcp-interface-reconfigure-2.3.2.patch"
+"
 
 CONFIG_CHECK="~NET_CLS_ACT ~NET_CLS_U32 ~NET_SCH_INGRESS ~NET_ACT_POLICE ~IPV6 ~TUN"
 MODULE_NAMES="openvswitch(net:${S}/datapath/linux)"
@@ -39,8 +37,8 @@ BUILD_TARGETS="all"
 pkg_setup() {
 	if use modules ; then
 		CONFIG_CHECK+=" ~!OPENVSWITCH"
-		kernel_is ge 3 10 0 || die "Linux >= 3.10.0 and <= 4.8 required for userspace modules"
-		kernel_is le 4 12 999 || die "Linux >= 3.10.0 and <= 4.12 required for userspace modules"
+		kernel_is ge 3 10 0 || die "Linux >= 3.10.0 and <= 5.8 required for userspace modules"
+		kernel_is le 5 8 999 || die "Linux >= 3.10.0 and <= 5.8 required for userspace modules"
 		linux-mod_pkg_setup
 	else
 		CONFIG_CHECK+=" ~OPENVSWITCH"
@@ -63,6 +61,10 @@ src_configure() {
 	# use monitor || export ovs_cv_python="no"
 	# pyside is staticly disabled
 	export ovs_cv_pyuic4="no"
+
+	# flake8 is primarily a style guide tool, running it as part of the tests
+	# in Gentoo does not make much sense, only breaks them: bug 607280
+	export ovs_cv_flake8="no"
 
 	local linux_config
 	use modules && linux_config="--with-linux=${KV_OUT_DIR}"
@@ -91,23 +93,26 @@ src_install() {
 			sed -e '1s|^.*$|#!/usr/bin/python|' -i utilities/"${SCRIPT}"
 			python_foreach_impl python_doscript utilities/"${SCRIPT}"
 		done
-		rm -r "${ED%/}"/usr/share/openvswitch/python || die
+		rm -r "${ED}"/usr/share/openvswitch/python || die
 	fi
 
 	keepdir /var/{lib,log}/openvswitch
 	keepdir /etc/ssl/openvswitch
 	fperms 0750 /etc/ssl/openvswitch
 
-	rm -rf "${ED%/}"/var/run || die
+	rm -rf "${ED}"/var/run || die
 
 	newconfd "${FILESDIR}/ovsdb-server_conf2" ovsdb-server
-	newconfd "${FILESDIR}/ovs-vswitchd_conf" ovs-vswitchd
+	newconfd "${FILESDIR}/ovs-vswitchd.confd-r2" ovs-vswitchd
 	newinitd "${FILESDIR}/ovsdb-server-r1" ovsdb-server
 	newinitd "${FILESDIR}/ovs-vswitchd-r1" ovs-vswitchd
 
-	systemd_dounit "${FILESDIR}/ovsdb-server.service"
-	systemd_dounit "${FILESDIR}/ovs-vswitchd.service"
-	systemd_newtmpfilesd "${FILESDIR}/openvswitch.tmpfiles" openvswitch.conf
+	if use systemd ; then
+		systemd_newunit "${FILESDIR}/ovsdb-server-r3.service" ovsdb-server.service
+		systemd_newunit "${FILESDIR}/ovs-vswitchd-r3.service" ovs-vswitchd.service
+		systemd_newunit rhel/usr_lib_systemd_system_ovs-delete-transient-ports.service ovs-delete-transient-ports.service
+		newtmpfiles "${FILESDIR}/openvswitch.tmpfiles" openvswitch.conf
+	fi
 
 	insinto /etc/logrotate.d
 	newins rhel/etc_logrotate.d_openvswitch openvswitch
@@ -118,18 +123,9 @@ src_install() {
 pkg_postinst() {
 	use modules && linux-mod_pkg_postinst
 
-	local pv
-	for pv in ${REPLACING_VERSIONS}; do
-		if ! version_is_at_least 1.9.0 ${pv} ; then
-			ewarn "The configuration database for Open vSwitch got moved in version 1.9.0 from"
-			ewarn "    /etc/openvswitch"
-			ewarn "to"
-			ewarn "    /var/lib/openvswitch"
-			ewarn "Please copy/move the database manually before running the schema upgrade."
-			ewarn "The PKI files are now supposed to go to /etc/ssl/openvswitch"
-		fi
-	done
+	tmpfiles_process openvswitch.conf
 
+	# only needed on non-systemd, but helps anyway
 	elog "Use the following command to create an initial database for ovsdb-server:"
 	elog "   emerge --config =${CATEGORY}/${PF}"
 	elog "(will create a database in /var/lib/openvswitch/conf.db)"
@@ -137,15 +133,15 @@ pkg_postinst() {
 }
 
 pkg_config() {
-	local db="${EROOT%/}"/var/lib/openvswitch/conf.db
+	local db="${EROOT%}"/var/lib/openvswitch/conf.db
 	if [[ -e "${db}" ]] ; then
 		einfo "Database '${db}' already exists, doing schema migration..."
 		einfo "(if the migration fails, make sure that ovsdb-server is not running)"
 		ovsdb-tool convert "${db}" \
-			"${EROOT%/}"/usr/share/openvswitch/vswitch.ovsschema || die "converting database failed"
+			"${EROOT}"/usr/share/openvswitch/vswitch.ovsschema || die "converting database failed"
 	else
 		einfo "Creating new database '${db}'..."
 		ovsdb-tool create "${db}" \
-			"${EROOT%/}"/usr/share/openvswitch/vswitch.ovsschema || die "creating database failed"
+			"${EROOT}"/usr/share/openvswitch/vswitch.ovsschema || die "creating database failed"
 	fi
 }
