Autogenerated tree updates.
merged:

  flora: 523a446b976b43c4ede7fd49048643aaf4812e42
  faustoo: 8cf33f71adbf52974f1e4f8443ef40cfd7de3969
  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  kit-fixups: afabb5ee7ee7dee5183a4c40abeb17db64058076

diff --git a/www-apps/cgit/templates/cgit.tmpl b/www-apps/cgit/templates/cgit.tmpl
--- a/www-apps/cgit/templates/cgit.tmpl
+++ b/www-apps/cgit/templates/cgit.tmpl
@@ -1,28 +1,32 @@
-# Copyright 1999-2018 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI="4"
+EAPI=7
+
+PYTHON_COMPAT=( {{python_compat}} )
 
 WEBAPP_MANUAL_SLOT="yes"
 
-inherit webapp eutils multilib user toolchain-funcs git-2
+inherit python-single-r1 toolchain-funcs user webapp
 
 [[ -z "${CGIT_CACHEDIR}" ]] && CGIT_CACHEDIR="/var/cache/${PN}/"
 
 DESCRIPTION="a fast web-interface for git repositories"
 HOMEPAGE="https://git.zx2c4.com/cgit/about"
-SRC_URI=""
-EGIT_REPO_URI="https://git.zx2c4.com/cgit"
+SRC_URI="{% for artifact in artifacts %}
+	{{ artifact.src_uri }}{% endfor %}
+"
 
 LICENSE="GPL-2"
 SLOT="0"
-KEYWORDS=""
+KEYWORDS="*"
 IUSE="doc +highlight +lua +jit"
 
-RDEPEND="
+RESTRICT="test"
+
+RDEPEND="${PYTHON_DEPS}
+	dev-libs/openssl:0=
 	dev-vcs/git
 	sys-libs/zlib
-	dev-libs/openssl:0
 	virtual/httpd-cgi
 	highlight? ( || ( dev-python/pygments app-text/highlight ) )
 	lua? ( jit? ( dev-lang/luajit ) !jit? ( dev-lang/lua ) )
@@ -37,27 +41,32 @@ DEPEND="${RDEPEND}
 pkg_setup() {
 	webapp_pkg_setup
 	enewuser "${PN}"
+	enewgroup "${PN}"
 }
 
 src_prepare() {
-	git submodule init || die
-	git submodule update || die
+	python_setup
 
-	echo "prefix = ${EPREFIX}/usr" >> cgit.conf
-	echo "libdir = ${EPREFIX}/usr/$(get_libdir)" >> cgit.conf
-	echo "CGIT_SCRIPT_PATH = ${MY_CGIBINDIR}" >> cgit.conf
-	echo "CGIT_DATA_PATH = ${MY_HTDOCSDIR}" >> cgit.conf
-	echo "CACHE_ROOT = ${CGIT_CACHEDIR}" >> cgit.conf
-	echo "DESTDIR = ${D}" >> cgit.conf
+	rmdir git || die
+	mv "${WORKDIR}"/git-{{git_ver}} git || die
+
+	echo "prefix = ${EPREFIX}/usr" >> cgit.conf || die "echo prefix failed"
+	echo "libdir = ${EPREFIX}/usr/$(get_libdir)" >> cgit.conf || die "echo libdir failed"
+	echo "CGIT_SCRIPT_PATH = ${MY_CGIBINDIR}" >> cgit.conf || die "echo CGIT_SCRIPT_PATH failed"
+	echo "CGIT_DATA_PATH = ${MY_HTDOCSDIR}" >> cgit.conf || die "echo CGIT_DATA_PATH failed"
+	echo "CACHE_ROOT = ${CGIT_CACHEDIR}" >> cgit.conf || die "echo CACHE_ROOT failed"
+	echo "DESTDIR = ${D}" >> cgit.conf || die "echo DESTDIR failed"
 	if use lua; then
 		if use jit; then
-			echo "LUA_PKGCONFIG = luajit" >> cgit.conf
+			echo "LUA_PKGCONFIG = luajit" >> cgit.conf || die "echo LUA_PKGCONFIG failed"
 		else
-			echo "LUA_PKGCONFIG = lua" >> cgit.conf
+			echo "LUA_PKGCONFIG = lua" >> cgit.conf || die "echo LUA_PKGCONFIG failed"
 		fi
 	else
-		echo "NO_LUA = 1" >> cgit.conf
+		echo "NO_LUA = 1" >> cgit.conf || die "echo NO_LUA failed"
 	fi
+
+	eapply_user
 }
 
 src_compile() {
@@ -82,6 +91,7 @@ src_install() {
 	keepdir "${CGIT_CACHEDIR}"
 	fowners ${PN}:${PN} "${CGIT_CACHEDIR}"
 	fperms 700 "${CGIT_CACHEDIR}"
+	python_fix_shebang .
 }
 
 pkg_postinst() {
