Autogenerated tree updates.
merged:

  flora: 523a446b976b43c4ede7fd49048643aaf4812e42
  faustoo: d6eacb18b01bf9b30948e331c85ca100ddec0882
  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  kit-fixups: 41ffbcfb69d2d0222cdad196ff62fd4043906849

diff --git a/net-misc/aria2/templates/aria2.tmpl b/net-misc/aria2/templates/aria2.tmpl
--- a/net-misc/aria2/templates/aria2.tmpl
+++ b/net-misc/aria2/templates/aria2.tmpl
@@ -1,33 +1,40 @@
-# Copyright 1999-2019 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI="6"
+EAPI=7
 
 inherit bash-completion-r1
 
 DESCRIPTION="A download utility with segmented downloading with BitTorrent support"
 HOMEPAGE="https://aria2.github.io/"
-SRC_URI="https://github.com/aria2/${PN}/releases/download/release-${PV}/${P}.tar.xz"
+SRC_URI="{{artifacts[0].src_uri}}"
 
-LICENSE="GPL-2"
-KEYWORDS="amd64 ~arm ~ppc ~ppc64 ~sparc x86 ~amd64-linux ~x86-linux"
+LICENSE="GPL-2+-with-openssl-exception"
+KEYWORDS="*"
 SLOT="0"
 IUSE="adns bittorrent +gnutls jemalloc libuv +libxml2 metalink +nettle nls sqlite scripts ssh ssl tcmalloc test xmlrpc"
+# xmlrpc has no explicit switch, it's turned out by any XML library
+# so metalink implicitly forces it on
+REQUIRED_USE="?? ( jemalloc tcmalloc )
+	metalink? ( xmlrpc )"
+RESTRICT="!test? ( test )"
 
-CDEPEND="sys-libs/zlib:0=
-	ssl? (
-		app-misc/ca-certificates
-		gnutls? ( >=net-libs/gnutls-1.2.9:0= )
-		!gnutls? ( dev-libs/openssl:0= ) )
+# Crazy GnuTLS/OpenSSL/etc. logic below:
+# 1. Those libraries are used for two purposes: TLS & MD.
+# 2. Upstream preferences are:
+#    1) gnutls [tls]
+#    2) !gnutls? -> openssl [tls+md]
+#    3) !openssl? -> nettle [md]
+#    4) !openssl? !nettle? -> gcrypt [md]
+#    5) !*? -> bundled md routines (we don't use them)
+# 3. There's also gmp usage for bittorrent with nettle.
+# 4. You can't really control features, just dependencies.
+# (we are skipping native Apple/Windows TLS support)
+#
+# We map this into:
+# ssl? -> openssl || (gnutls + (nettle || libgcrypt ))
+# !ssl? -> nettle || libgcrypt
+RDEPEND="sys-libs/zlib:0=
 	adns? ( >=net-dns/c-ares-1.5.0:0= )
-	bittorrent? (
-		ssl? (
-			gnutls? (
-				nettle? ( >=dev-libs/nettle-2.4:0=[gmp] >=dev-libs/gmp-6:0= )
-				!nettle? ( >=dev-libs/libgcrypt-1.2.2:0= ) ) )
-		!ssl? (
-			nettle? ( >=dev-libs/nettle-2.4:0=[gmp] >=dev-libs/gmp-6:0= )
-			!nettle? ( >=dev-libs/libgcrypt-1.2.2:0= ) ) )
 	jemalloc? ( dev-libs/jemalloc )
 	libuv? ( >=dev-libs/libuv-1.13:0= )
 	metalink? (
@@ -35,25 +42,46 @@ CDEPEND="sys-libs/zlib:0=
 		!libxml2? ( dev-libs/expat:0= ) )
 	sqlite? ( dev-db/sqlite:3= )
 	ssh? ( net-libs/libssh2:= )
+	ssl? (
+		app-misc/ca-certificates
+		gnutls? (
+			>=net-libs/gnutls-1.2.9:0=
+			nettle? (
+				>=dev-libs/nettle-2.4:0=
+				bittorrent? (
+					>=dev-libs/nettle-2.4:0=[gmp]
+					>=dev-libs/gmp-6:0=
+				)
+			)
+			!nettle? ( >=dev-libs/libgcrypt-1.2.2:0= )
+		)
+		!gnutls? (
+			dev-libs/openssl:0=
+		)
+	)
+	!ssl? (
+		nettle? (
+			>=dev-libs/nettle-2.4:0=
+			bittorrent? (
+				>=dev-libs/nettle-2.4:0=[gmp]
+				>=dev-libs/gmp-6:0=
+			)
+		)
+		!nettle? ( >=dev-libs/libgcrypt-1.2.2:0= )
+	)
 	tcmalloc? ( dev-util/google-perftools )
 	xmlrpc? (
 		libxml2? ( >=dev-libs/libxml2-2.6.26:2= )
 		!libxml2? ( dev-libs/expat:0= ) )"
 
-DEPEND="${CDEPEND}
-	app-arch/xz-utils
-	virtual/pkgconfig
-	nls? ( sys-devel/gettext )
+DEPEND="${RDEPEND}
 	test? ( >=dev-util/cppunit-1.12.0:0 )"
-RDEPEND="${CDEPEND}
+RDEPEND+="
 	nls? ( virtual/libiconv virtual/libintl )
 	scripts? ( dev-lang/ruby )"
-
-# xmlrpc has no explicit switch, it's turned out by any XML library
-# so metalink implicitly forces it on
-REQUIRED_USE="?? ( jemalloc tcmalloc )
-	metalink? ( xmlrpc )"
-RESTRICT="!test? ( test )"
+BDEPEND="app-arch/xz-utils
+	virtual/pkgconfig
+	nls? ( sys-devel/gettext )"
 
 pkg_setup() {
 	if use scripts && ! use xmlrpc; then
@@ -63,11 +91,13 @@ pkg_setup() {
 }
 
 src_prepare() {
-	eapply "${FILESDIR}"/${P}-make_unique.patch
-	# https://bugs.gentoo.org/674622 (CVE-2019-3500)
-	eapply "${FILESDIR}"/${P}-mask-headers.patch
 	default
 	sed -i -e "s|/tmp|${T}|" test/*.cc test/*.txt || die "sed failed"
+	# Fails with USE=bittorrent && FEATURES=network-sandbox
+	sed -i -E \
+		-e '/^@ENABLE_BITTORRENT_TRUE@	LpdMessageDispatcherTest/d' \
+		-e '/^@ENABLE_BITTORRENT_TRUE@	LpdMessageReceiverTest/d' \
+		test/Makefile.in || die
 }
 
 src_configure() {
@@ -94,30 +124,28 @@ src_configure() {
 		$(use_with tcmalloc)
 	)
 
-	# SSL := gnutls / openssl
-	# USE=ssl
-	#  + USE=gnutls -> gnutls
-	#  + USE=-gnutls -> openssl
-
-	if use ssl; then
-		myconf+=( $(use_with gnutls) $(use_with !gnutls openssl) )
+	# See TLS/MD logic described above deps.
+	if use ssl && ! use gnutls; then
+		# 1. if ssl & !gnutls, use openssl and disable gnutls
+		myconf+=( --without-gnutls --with-openssl )
 	else
-		myconf+=( --without-gnutls --without-openssl )
-	fi
+		myconf+=(
+			# 2. otherwise, disable openssl
+			--without-openssl
+			# 3. if ssl & gnutls, use gnutls
+			$(use_with ssl gnutls)
 
-	# message-digest := nettle / gcrypt / openssl
-	# bignum := nettle+gmp / gcrypt / openssl
-	# bittorrent := message-digest + bignum
-	# USE=bittorrent
-	#  + USE=(ssl -gnutls) -> openssl
-	#  + USE=nettle -> nettle+gmp
-	#  + USE=-nettle -> gcrypt
+			# 4. switch between nettle & libgcrypt
+			$(use_with nettle libnettle)
+			$(use_with !nettle libgcrypt)
+		)
 
-	if use !bittorrent || use ssl && use !gnutls; then
-		myconf+=( --without-libgcrypt --without-libnettle --without-libgmp )
-	else
-		myconf+=( $(use_with !nettle libgcrypt)
-			$(use_with nettle libnettle) $(use_with nettle libgmp) )
+		# 5. if bittorrent is used along with nettle, use libgmp
+		if use bittorrent && use nettle; then
+			myconf+=( --with-libgmp )
+		else
+			myconf+=( --without-libgmp )
+		fi
 	fi
 
 	# metalink+xmlrpc := libxml2 / expat
@@ -140,8 +168,7 @@ src_configure() {
 
 src_install() {
 	default
-	rm -rf "${D}"/usr/share/doc/aria2 \
-		"${D}"/usr/share/doc/${PF}/README{,.html}
+	rm -r "${ED}"/usr/share/doc/${PF}/README{,.html} || die
 
 	dobashcomp doc/bash_completion/aria2c
 	use scripts && dobin doc/xmlrpc/aria2{mon,rpc}
